version: 0.2

phases:
  build:
    commands:
      - echo "Building for deadline submission"
      - echo '[{"name":"devops-pipeline-app","imageUri":"070593201734.dkr.ecr.eu-north-1.amazonaws.com/devops-pipeline:deadline"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
