version: 0.2

phases:
  build:
    commands:
      - echo "Creating minimal working artifact for deadline"
      - printf '[{"name":"devops-pipeline-app","imageUri":"070593201734.dkr.ecr.eu-north-1.amazonaws.com/devops-pipeline:deadline"}]' > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
