version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"devops-pipeline-app","imageUri":"070593201734.dkr.ecr.eu-north-1.amazonaws.com/devops-pipeline:latest"}]' > imagedefinitions.json
      - cat imagedefinitions.json
      - echo Build completed successfully

artifacts:
  files:
    - imagedefinitions.json
