apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline-app
  labels:
    app: devops-pipeline-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-pipeline-app
  template:
    metadata:
      labels:
        app: devops-pipeline-app
    spec:
      containers:
      - name: app
        image: nginx:latest  # This will be replaced by CodePipeline
        ports:
        - containerPort: 5000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
