apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    database-url: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
    api-key: AgAKAoiQm1dBMRBZpTgzrSrE6T...
  template:
    metadata:
      name: app-secrets
      namespace: default
    type: Opaque
