name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: cd app && pip install -r requirements.txt
    - run: cd app && python -c "import app; print('✅ App works')"
    - run: cd app && docker build -t devops-pipeline:$GITHUB_SHA .
